const LOTTO_URL="https://www.lotto.de/lotto-6aus49/lottozahlen";
const EURO_URL="https://www.eurojackpot.de/";
const headers={"user-agent":"Mozilla/5.0 (compatible; LottoZentrale/1.1)","accept-language":"de-DE,de;q=0.9","accept":"text/html,application/xhtml+xml"};
function decode(s){return s.replace(/&nbsp;|&#160;/g,' ').replace(/&amp;/g,'&').replace(/&auml;/g,'ä').replace(/&ouml;/g,'ö').replace(/&uuml;/g,'ü').replace(/&szlig;/g,'ß').replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(+n))}
function strip(html){return decode(html.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ')).trim()}
function uniqueDraws(draws){const seen=new Set();return draws.filter(d=>{const k=d.date+'|'+d.numbers.join(',')+'|'+(d.special||[]).join(',');if(seen.has(k))return false;seen.add(k);return true}).sort((a,b)=>dateValue(b.date)-dateValue(a.date)).slice(0,5)}
function dateValue(s){const m=s.match(/(\d{2})\.(\d{2})\.(\d{4})/);if(m)return new Date(+m[3],+m[2]-1,+m[1]).getTime();const x=Date.parse(s);return Number.isNaN(x)?0:x}
function parseLotto(html){const text=strip(html),out=[];const rx=/(?:Ziehung(?:\s+vom)?\s*)?(Mittwoch|Samstag)[,\s]+(\d{2}\.\d{2}\.\d{4})([\s\S]{0,420}?)(?=(?:Mittwoch|Samstag)[,\s]+\d{2}\.\d{2}\.\d{4}|$)/gi;let m;while((m=rx.exec(text))){const part=m[3];const superM=part.match(/Superzahl\s*(\d)/i);const before=superM?part.slice(0,superM.index):part;const nums=(before.match(/\b(?:[1-9]|[1-4]\d)\b/g)||[]).map(Number).filter(n=>n>=1&&n<=49);if(nums.length>=6)out.push({date:m[2],numbers:nums.slice(0,6).sort((a,b)=>a-b),special:superM?[+superM[1]]:[]})}
if(out.length)return uniqueDraws(out);
const generic=/Ziehung\s+vom\s+(Mittwoch|Samstag),?\s*(\d{2}\.\d{2}\.\d{4})([\s\S]{0,300})/gi;while((m=generic.exec(text))){const nums=(m[3].match(/\b(?:[1-9]|[1-4]\d)\b/g)||[]).map(Number).filter(n=>n<=49);if(nums.length>=6)out.push({date:m[2],numbers:nums.slice(0,6).sort((a,b)=>a-b),special:[]})}return uniqueDraws(out)}
function parseEuro(html){const text=strip(html),out=[];const rx=/Gewinnzahlen\s+(Dienstag|Freitag),\s*(\d{2}\.\d{2}\.\d{4})\s+((?:\d{1,2}\s+){4}\d{1,2})\s+Eurozahlen\s+(\d{1,2})\s+(\d{1,2})/gi;let m;while((m=rx.exec(text))){out.push({date:m[2],numbers:m[3].trim().split(/\s+/).map(Number).sort((a,b)=>a-b),special:[+m[4],+m[5]].sort((a,b)=>a-b)})}return uniqueDraws(out)}
exports.handler=async()=>{try{const [lr,er]=await Promise.all([fetch(LOTTO_URL,{headers}),fetch(EURO_URL,{headers})]);if(!lr.ok||!er.ok)throw new Error(`Quellstatus Lotto ${lr.status}, Euro ${er.status}`);const [lh,eh]=await Promise.all([lr.text(),er.text()]);const lotto=parseLotto(lh),eurojackpot=parseEuro(eh);return{statusCode:200,headers:{"content-type":"application/json; charset=utf-8","cache-control":"public, max-age=600, s-maxage=600"},body:JSON.stringify({updatedAt:new Date().toLocaleString('de-DE',{timeZone:'Europe/Berlin'}),source:'LOTTO.de / Eurojackpot.de',draws:{lotto,eurojackpot},freq:null,debug:{lottoFound:lotto.length,euroFound:eurojackpot.length}})}}catch(error){return{statusCode:502,headers:{"content-type":"application/json; charset=utf-8"},body:JSON.stringify({error:'Live-Daten konnten nicht geladen werden.',detail:error.message})}}};
